import { useQuery } from '@tanstack/react-query';
import { Activity, Clock3, DatabaseZap, ShieldCheck } from 'lucide-react';
import { apiFetch } from '../lib/api';
import { Card, EmptyState, MetricTable, Notice, PageHeader, SectionHeading, StatusPill } from '../components/Ui';
import { DataErrorBanner } from './shared';

interface WacReportingHealth {freshness:Array<Record<string,unknown>>;syncRuns:Array<Record<string,unknown>>;issues?:Array<Record<string,unknown>>;accounts:Array<Record<string,unknown>>;schemaVersion:string;provenance?:string}
interface HealthResponse {checkedAt:string;timezone:string;states:Array<Record<string,unknown>>;facts:Array<Record<string,unknown>>;recentRuns:Array<Record<string,unknown>>;wacReporting:WacReportingHealth|null}

export function HealthPage(){
  const query=useQuery({queryKey:['health'],queryFn:()=>apiFetch<HealthResponse>('/api/health'),retry:1,refetchInterval:60_000});
  const data=query.data??{checkedAt:new Date().toISOString(),timezone:'Asia/Jakarta',states:[],facts:[],recentRuns:[],wacReporting:null};
  return <><PageHeader eyebrow="Operations" title="Data health & ingestion" description="Source coverage, warehouse freshness and recent scheduled runs. This internal view does not change campaign state." aside={<button className="button secondary" onClick={()=>query.refetch()}><Activity size={15}/> Refresh status</button>}/><DataErrorBanner message={query.error?.message}/>
    <Notice type="secure" title="Read-only boundary"><p>The API serves database reads only. Incremental refresh is protected by CRON_SECRET; full history is a separately run owner operation.</p></Notice>
    <div className="health-summary"><Card><DatabaseZap/><div><span>Registered states</span><strong>{data.states.length||'—'}</strong></div></Card><Card><ShieldCheck/><div><span>Fact sources</span><strong>{data.facts.length||'—'}</strong></div></Card><Card><Clock3/><div><span>Last checked</span><strong>{new Date(data.checkedAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'})}</strong></div></Card></div>
    <section className="content-section"><SectionHeading kicker="Source state" title="Connection inventory" description="Seeded states are expectations; connected states require a successful ingestion."/><Card>{data.states.length?<div className="table-scroll"><table><thead><tr><th>Source</th><th>Status</th><th>Message</th><th>Last success</th></tr></thead><tbody>{data.states.map((row)=><tr key={String(row.source)}><td><strong>{String(row.source)}</strong></td><td><StatusPill status={String(row.status).includes('connected')?'live':String(row.status).includes('qa_')?'warning':String(row.status).includes('seeded')?'seeded':'unavailable'} label={String(row.status)}/></td><td>{String(row.message??'—')}</td><td>{String(row.last_success_at??'Unavailable')}</td></tr>)}</tbody></table></div>:<EmptyState message="Connect DATABASE_URL and apply the seed to populate source health."/>}</Card></section>
    <section className="content-section"><SectionHeading kicker="Warehouse" title="Fact freshness"/><Card>{data.facts.length?<div className="table-scroll"><table><thead><tr><th>Platform</th><th>Account</th><th>Latest report</th><th>Ingested</th><th>Rows</th></tr></thead><tbody>{data.facts.map((row)=><tr key={`${row.platform}-${row.account_id}`}><td><strong>{String(row.platform)}</strong></td><td className="mono">{String(row.account_id)}</td><td>{String(row.latest_report_date)}</td><td>{String(row.last_ingested_at)}</td><td>{String(row.row_count)}</td></tr>)}</tbody></table></div>:<EmptyState message="The fact warehouse is empty until the first backfill succeeds."/>}</Card></section>
    <section className="content-section"><SectionHeading kicker="WAC contract" title="Reporting freshness & sync status" description="Sanitized owner-reporting metadata for the Jaecoo paid accounts; raw connector payloads and credentials are not exposed." action={data.wacReporting?<StatusPill status={data.wacReporting.provenance==='authorized_read_only_snapshot'?'partial':'live'} label={data.wacReporting.provenance==='authorized_read_only_snapshot'?'snapshot available':`schema ${data.wacReporting.schemaVersion}`}/>:<StatusPill status="unavailable" label="awaiting WAC sync"/>}/>{data.wacReporting?.provenance==='authorized_read_only_snapshot'&&<Notice type="warning" title="Snapshot provenance"><p>This read-only capture reflects WAC warehouse state at import time. It does not prove that this dashboard's scheduled ingestion has run.</p></Notice>}<div className="split-grid equal"><Card><div className="card-head"><div><strong>Registered paid accounts</strong><span>account_list</span></div></div><MetricTable rows={data.wacReporting?.accounts??[]} emptyMessage="No WAC account inventory has been captured."/></Card><Card><div className="card-head"><div><strong>Recent WAC sync runs</strong><span>reporting_sync_status</span></div></div><MetricTable rows={data.wacReporting?.syncRuns??[]} emptyMessage="No WAC reporting sync status has been captured."/></Card></div><div className="split-grid equal"><Card><div className="card-head"><div><strong>Reporting freshness</strong><span>reporting_freshness</span></div></div><MetricTable rows={data.wacReporting?.freshness??[]} emptyMessage="No WAC freshness rows have been captured."/></Card><Card><div className="card-head"><div><strong>Unresolved WAC issues</strong><span>reporting_sync_status</span></div></div><MetricTable rows={data.wacReporting?.issues??[]} emptyMessage="No unresolved Jaecoo reporting issues were captured."/></Card></div></section>
    <section className="content-section"><SectionHeading kicker="Run history" title="Recent ingestion attempts"/><Card>{data.recentRuns.length?<div className="table-scroll"><table><thead><tr><th>Source</th><th>Window</th><th>Status</th><th>Rows</th><th>Started</th></tr></thead><tbody>{data.recentRuns.map((row)=><tr key={String(row.id)}><td>{String(row.source)}</td><td>{String(row.window_start)} → {String(row.window_end)}</td><td><StatusPill status={row.status==='complete'?'live':row.status==='running'?'partial':'unavailable'} label={String(row.status)}/></td><td>{String(row.rows_written)}</td><td>{String(row.started_at)}</td></tr>)}</tbody></table></div>:<EmptyState compact message="No ingestion runs have been recorded."/>}</Card></section>
  </>;
}
